vich_uploader:
    db_driver: orm

    mappings:
        users_images:
            uri_prefix: '%app.path.users_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.users_images%'

            namer: 'Vich\UploaderBundle\Naming\UniqidNamer' 
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true